### ISSUE TITLE
Usage with SvelteKit?

### ISSUE THREAD

**Issue by danawoodman** [furudean/svelte-persistent-store#19]
I'm attempting to use this in SvelteKit but getting:

```
TypeError: Failed to fetch dynamically imported module:
```

Is there any config needed for Vite/Svelte to get this working?

**Comment by furudean** [comment]
There shouldn't be anything special needed. I use this in a Svelte Kit project without issue. Do you have a repro I could look at?

**Comment by danawoodman** [comment]
I just tried it again with the latest version of Kit, and it is failing with the following:

```
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "util"

    .svelte-kit/output/server/entries/pages/_page.svelte.js:3:14:
      3 │ import e from "util";
        ╵               ~~~~~~

  The package "util" wasn't found on the file system
  but is built into node. Are you trying to bundle for
  node? You can use "platform: 'node'" to do that,
  which will remove this error.

✘ [ERROR] Could not resolve "crypto"

    .svelte-kit/output/server/entries/pages/_page.svelte.js:4:14:
      4 │ import r from "crypto";
        ╵               ~~~~~~~~

  The package "crypto" wasn't found on the file system
  but is built into node. Are you trying to bundle for
  node? You can use "platform: 'node'" to do that,
  which will remove this error.
```

**Comment by furudean** [comment]
Those errors don't make sense to me. This lib doesn't use any imports like `crypto` or `util`.

**Comment by danawoodman** [comment]
Yes, strange to me too, but I could isolate those errors down to when I used this library. It appears to occur with adapter-cloudflare in particular. I'll follow up if I have more details

**Comment by danawoodman** [comment]
Just tried with a totally bare project with adapter-cloudflare. Importing this library breaks the build, nothing else installed.

**Comment by furudean** [comment]
I'm struggling to wrap my head around why this would happen... The only import used is `import { writable } from "svelte/store"`. I could implement the store behavior myself to get rid of the dependency but this seems like a bigger problem with Svelte Kit doesn't handle this case correctly.

**Comment by danawoodman** [comment]
Wait.... I think I made a big booboo, I confused this with https://github.com/MacFJA/svelte-persistent-store 🤦 

The issue there is their use of `cyrup` package: https://github.com/MacFJA/svelte-persistent-store/issues/31

Sorry for the confusion!!!!

**Comment by danawoodman** [comment]
I just switched to yours and it works great! The identical package names threw me, sorry again 😅
